# Generated by Django 2.1.5 on 2020-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0002_auto_20201106_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emergency',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='mobile',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='telephone',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
