# Generated by Django 2.1.5 on 2020-11-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0003_auto_20201106_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
