# Generated by Django 2.1.5 on 2020-11-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0004_employees_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(default='Work Email', max_length=254),
        ),
    ]
