# Generated by Django 2.1.5 on 2020-11-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0005_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emergency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
