# Generated by Django 2.1.5 on 2020-11-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0006_auto_20201107_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='position',
            new_name='department',
        ),
    ]
