# Generated by Django 2.1.5 on 2020-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0008_auto_20201108_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
