# Generated by Django 2.1.5 on 2020-11-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0010_auto_20201108_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
