# Generated by Django 2.1.5 on 2020-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_record', '0011_auto_20201108_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
